[31m2025-06-01 00:00:36 [error] relation "userWorkflowTasks" does not exist [39m meta={"err":"Error\n    at Query.run (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/postgres/query.js:76:25)\n    at <anonymous> (/root/www/my-nocobase-app/node_modules/sequelize/src/sequelize.js:650:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.rawSelect (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/abstract/query-interface.js:1043:18)\n    at async Function.aggregate (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2067:19)\n    at async Function.count (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2124:20)\n    at async _Repository.count (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:157:12)\n    at async _Repository.findAndCount (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:282:19)\n    at async listWithPagination (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:76:27)\n    at async Object.list (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:99:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)"} module=userWorkflowTasks submodule=listMine method=error-handler app=main reqId=ebd2b29b-014b-4b62-bee8-233ab27e9591 dataSourceKey=main
[31m2025-06-01 00:01:40 [error] relation "userWorkflowTasks" does not exist [39m meta={"err":"Error\n    at Query.run (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/postgres/query.js:76:25)\n    at <anonymous> (/root/www/my-nocobase-app/node_modules/sequelize/src/sequelize.js:650:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.rawSelect (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/abstract/query-interface.js:1043:18)\n    at async Function.aggregate (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2067:19)\n    at async Function.count (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2124:20)\n    at async _Repository.count (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:157:12)\n    at async _Repository.findAndCount (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:282:19)\n    at async listWithPagination (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:76:27)\n    at async Object.list (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:99:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)"} module=userWorkflowTasks submodule=listMine method=error-handler app=main reqId=70427ab8-eb0a-4156-a5ae-9a2c7de06856 dataSourceKey=main
[31m2025-06-01 00:04:47 [error] relation "userWorkflowTasks" does not exist [39m meta={"err":"Error\n    at Query.run (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/postgres/query.js:76:25)\n    at <anonymous> (/root/www/my-nocobase-app/node_modules/sequelize/src/sequelize.js:650:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.rawSelect (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/abstract/query-interface.js:1043:18)\n    at async Function.aggregate (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2067:19)\n    at async Function.count (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2124:20)\n    at async _Repository.count (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:157:12)\n    at async _Repository.findAndCount (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:282:19)\n    at async listWithPagination (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:76:27)\n    at async Object.list (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:99:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)"} module=userWorkflowTasks submodule=listMine method=error-handler app=main reqId=c3868513-9a86-48b0-ba9d-ee00e097eab4 dataSourceKey=main
[31m2025-06-01 00:04:47 [error] relation "userWorkflowTasks" does not exist [39m meta={"err":"Error\n    at Query.run (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/postgres/query.js:76:25)\n    at <anonymous> (/root/www/my-nocobase-app/node_modules/sequelize/src/sequelize.js:650:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.rawSelect (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/abstract/query-interface.js:1043:18)\n    at async Function.aggregate (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2067:19)\n    at async Function.count (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2124:20)\n    at async _Repository.count (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:157:12)\n    at async _Repository.findAndCount (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:282:19)\n    at async listWithPagination (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:76:27)\n    at async Object.list (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:99:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)"} module=userWorkflowTasks submodule=listMine method=error-handler app=main reqId=18460424-768e-4774-a8f6-2ae028e7c8e2 dataSourceKey=main
[31m2025-06-01 00:06:45 [error] Unauthenticated. Please sign in to continue.[39m meta={"err":"UnauthorizedError: Unauthenticated. Please sign in to continue.\n    at Object.throw (/root/www/my-nocobase-app/node_modules/koa/lib/context.js:97:11)\n    at BasicAuth.checkToken (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/base/auth.js:88:21)\n    at BasicAuth.check (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/base/auth.js:193:79)\n    at AuthManagerMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/auth-manager.js:121:35)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async validateFilterParams (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/validate-filter-params.js:39:12)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/plugin-locale-tester/dist/server/plugin.js:56:7\n    at async setMainDepartment (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-main-department.js:33:3)\n    at async resetUserDepartmentsCache (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/reset-user-departments-cache.js:33:3)\n    at async destroyDepartmentCheck (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/destroy-department-check.js:57:3)\n    at async handleFieldSourceMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-data-source-main/dist/server/server.js:443:7)\n    at async mergeReverseFieldWhenSaveCollectionField (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-data-source-main/dist/server/server.js:417:7)\n    at async parseToken (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-public-forms/dist/server/plugin.js:175:5)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/plugin-multi-app-manager/dist/server/server.js:364:7\n    at async blockChinaRegionList (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-field-china-region/dist/server/index.js:57:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/plugin-users/dist/server/server.js:223:7"} module=kanban_programacoes submodule=list method=error-handler app=main reqId=b84f0d7d-2285-442c-9422-8f7dd74aab7b dataSourceKey=main
[31m2025-06-01 00:18:03 [error] relation "userWorkflowTasks" does not exist [39m meta={"err":"Error\n    at Query.run (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/postgres/query.js:76:25)\n    at <anonymous> (/root/www/my-nocobase-app/node_modules/sequelize/src/sequelize.js:650:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.rawSelect (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/abstract/query-interface.js:1043:18)\n    at async Function.aggregate (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2067:19)\n    at async Function.count (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2124:20)\n    at async _Repository.count (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:157:12)\n    at async _Repository.findAndCount (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:282:19)\n    at async listWithPagination (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:76:27)\n    at async Object.list (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:99:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)"} module=userWorkflowTasks submodule=listMine method=error-handler app=main reqId=56cf5cad-b54e-4792-8741-15a34b5e3cf1 dataSourceKey=main
[31m2025-06-01 00:18:07 [error] relation "userWorkflowTasks" does not exist [39m meta={"err":"Error\n    at Query.run (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/postgres/query.js:76:25)\n    at <anonymous> (/root/www/my-nocobase-app/node_modules/sequelize/src/sequelize.js:650:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.rawSelect (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/abstract/query-interface.js:1043:18)\n    at async Function.aggregate (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2067:19)\n    at async Function.count (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2124:20)\n    at async _Repository.count (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:157:12)\n    at async _Repository.findAndCount (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:282:19)\n    at async listWithPagination (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:76:27)\n    at async Object.list (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:99:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)"} module=userWorkflowTasks submodule=listMine method=error-handler app=main reqId=d5cbd8c8-60db-46e6-8f24-8db862e1fc12 dataSourceKey=main
[31m2025-06-01 00:18:40 [error] relation "userWorkflowTasks" does not exist [39m meta={"err":"Error\n    at Query.run (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/postgres/query.js:76:25)\n    at <anonymous> (/root/www/my-nocobase-app/node_modules/sequelize/src/sequelize.js:650:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.rawSelect (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/abstract/query-interface.js:1043:18)\n    at async Function.aggregate (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2067:19)\n    at async Function.count (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2124:20)\n    at async _Repository.count (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:157:12)\n    at async _Repository.findAndCount (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:282:19)\n    at async listWithPagination (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:76:27)\n    at async Object.list (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:99:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)"} module=userWorkflowTasks submodule=listMine method=error-handler app=main reqId=2be71184-0298-4605-a79f-df5000df2bea dataSourceKey=main
[31m2025-06-01 00:18:43 [error] relation "userWorkflowTasks" does not exist [39m meta={"err":"Error\n    at Query.run (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/postgres/query.js:76:25)\n    at <anonymous> (/root/www/my-nocobase-app/node_modules/sequelize/src/sequelize.js:650:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async PostgresQueryInterface.rawSelect (/root/www/my-nocobase-app/node_modules/sequelize/src/dialects/abstract/query-interface.js:1043:18)\n    at async Function.aggregate (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2067:19)\n    at async Function.count (/root/www/my-nocobase-app/node_modules/sequelize/src/model.js:2124:20)\n    at async _Repository.count (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:157:12)\n    at async _Repository.findAndCount (/root/www/my-nocobase-app/node_modules/@nocobase/database/lib/repository.js:282:19)\n    at async listWithPagination (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:76:27)\n    at async Object.list (/root/www/my-nocobase-app/node_modules/@nocobase/actions/lib/actions/list.js:99:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)"} module=userWorkflowTasks submodule=listMine method=error-handler app=main reqId=74ea5f9e-ece7-4963-8f07-b47b435c6bdb dataSourceKey=main
[31m2025-06-01 00:32:58 [error] No permissions                              [39m meta={"err":"ForbiddenError: No permissions\n    at Object.throw (/root/www/my-nocobase-app/node_modules/koa/lib/context.js:97:11)\n    at middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:351:20)\n    at dispatch (/root/www/my-nocobase-app/node_modules/koa-compose/index.js:42:32)\n    at parseACL (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-public-forms/dist/server/plugin.js:179:14)\n    at dispatch (/root/www/my-nocobase-app/node_modules/koa-compose/index.js:42:32)\n    at /root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:466:18\n    at dispatch (/root/www/my-nocobase-app/node_modules/koa-compose/index.js:42:32)\n    at /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)\n    at async setCurrentRole (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/middlewares/setCurrentRole.js:87:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async app.resourcer.use.group (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-api-keys/dist/server/plugin.js:62:9)\n    at async AuthManagerMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/auth-manager.js:125:7)\n    at async validateFilterParams (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/validate-filter-params.js:39:12)"} module=kanban_programacoes submodule=list method=error-handler app=main reqId=94af58e8-a755-4d9f-89ef-9bb68a2a6c0e dataSourceKey=main
[31m2025-06-01 00:34:01 [error] No permissions                              [39m meta={"err":"ForbiddenError: No permissions\n    at Object.throw (/root/www/my-nocobase-app/node_modules/koa/lib/context.js:97:11)\n    at middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:351:20)\n    at dispatch (/root/www/my-nocobase-app/node_modules/koa-compose/index.js:42:32)\n    at parseACL (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-public-forms/dist/server/plugin.js:179:14)\n    at dispatch (/root/www/my-nocobase-app/node_modules/koa-compose/index.js:42:32)\n    at /root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:466:18\n    at dispatch (/root/www/my-nocobase-app/node_modules/koa-compose/index.js:42:32)\n    at /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)\n    at async setCurrentRole (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/middlewares/setCurrentRole.js:87:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async app.resourcer.use.group (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-api-keys/dist/server/plugin.js:62:9)\n    at async AuthManagerMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/auth-manager.js:125:7)\n    at async validateFilterParams (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/validate-filter-params.js:39:12)"} module=kanban_programacoes submodule=list method=error-handler app=main reqId=e67ee61d-7e0c-40b9-b446-cd1bf5c78697 dataSourceKey=main
[31m2025-06-01 00:36:06 [error] No permissions                              [39m meta={"err":"ForbiddenError: No permissions\n    at Object.throw (/root/www/my-nocobase-app/node_modules/koa/lib/context.js:97:11)\n    at middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:351:20)\n    at dispatch (/root/www/my-nocobase-app/node_modules/koa-compose/index.js:42:32)\n    at parseACL (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-public-forms/dist/server/plugin.js:179:14)\n    at dispatch (/root/www/my-nocobase-app/node_modules/koa-compose/index.js:42:32)\n    at /root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:466:18\n    at dispatch (/root/www/my-nocobase-app/node_modules/koa-compose/index.js:42:32)\n    at /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)\n    at async setCurrentRole (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/middlewares/setCurrentRole.js:87:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async app.resourcer.use.group (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-api-keys/dist/server/plugin.js:62:9)\n    at async AuthManagerMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/auth-manager.js:125:7)\n    at async validateFilterParams (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/validate-filter-params.js:39:12)"} module=kanban_programacoes submodule=list method=error-handler app=main reqId=6f2cf8bf-9490-4b3c-8216-a9e55ded8194 dataSourceKey=main
[31m2025-06-01 01:17:11 [error] Cannot read properties of undefined (reading 'repository')[39m stack=TypeError: Cannot read properties of undefined (reading 'repository')
    at get userRepository (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/base/auth.js:54:32)
    at /root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/base/auth.js:113:18
    at /root/www/my-nocobase-app/node_modules/cache-manager/dist/caching.js:58:42
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async coalesceAsync (/root/www/my-nocobase-app/node_modules/promise-coalesce/src/coalesce.ts:27:22)
    at async _Cache.wrap (/root/www/my-nocobase-app/node_modules/@nocobase/cache/lib/cache.js:58:12)
    at async BasicAuth.checkToken (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/base/auth.js:111:27)
    at async _AsyncEmitter.<anonymous> (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-auth/dist/server/plugin.js:176:17) module=application app=main reqId=d97c8340-629a-47f2-b781-59f74bb36958 dataSourceKey=main
[31m2025-06-01 02:17:41 [error] Cannot read properties of undefined (reading 'getConfig')[39m stack=TypeError: Cannot read properties of undefined (reading 'getConfig')
    at BasicAuth.checkToken (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/base/auth.js:146:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _AsyncEmitter.<anonymous> (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-auth/dist/server/plugin.js:176:17) module=application app=main reqId=b4d7a8af-0ccb-49c8-aa9c-04aaba98e2d3 dataSourceKey=main
[31m2025-06-01 02:18:07 [error] Erro interno do servidor ao atualizar programação[39m meta={"err":"InternalServerError: Erro interno do servidor ao atualizar programação\n    at Object.throw (/root/www/my-nocobase-app/node_modules/koa/lib/context.js:97:11)\n    at updateWeekDay (/root/www/my-nocobase-app/packages/plugins/@sigmacore/kanban/src/server/plugin.ts:161:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)\n    at async setCurrentRole (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/middlewares/setCurrentRole.js:87:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async app.resourcer.use.group (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-api-keys/dist/server/plugin.js:62:9)\n    at async AuthManagerMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/auth-manager.js:125:7)\n    at async validateFilterParams (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/validate-filter-params.js:39:12)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/plugin-locale-tester/dist/server/plugin.js:56:7"} module=kanban_programacoes submodule=updateWeekDay method=error-handler app=main reqId=b8dfaa91-9138-42fd-98f9-d42798ac9e7a dataSourceKey=main
[31m2025-06-01 02:18:39 [error] Erro interno do servidor ao atualizar programação[39m meta={"err":"InternalServerError: Erro interno do servidor ao atualizar programação\n    at Object.throw (/root/www/my-nocobase-app/node_modules/koa/lib/context.js:97:11)\n    at updateWeekDay (/root/www/my-nocobase-app/packages/plugins/@sigmacore/kanban/src/server/plugin.ts:161:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)\n    at async setCurrentRole (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/middlewares/setCurrentRole.js:87:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async app.resourcer.use.group (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-api-keys/dist/server/plugin.js:62:9)\n    at async AuthManagerMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/auth-manager.js:125:7)\n    at async validateFilterParams (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/validate-filter-params.js:39:12)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/plugin-locale-tester/dist/server/plugin.js:56:7"} module=kanban_programacoes submodule=updateWeekDay method=error-handler app=main reqId=42947289-f75e-43f1-8010-079a94a1a21e dataSourceKey=main
[31m2025-06-01 02:20:54 [error] Cannot read properties of undefined (reading 'getConfig')[39m stack=TypeError: Cannot read properties of undefined (reading 'getConfig')
    at BasicAuth.checkToken (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/base/auth.js:146:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _AsyncEmitter.<anonymous> (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-auth/dist/server/plugin.js:176:17) module=application app=main reqId=c4b35a4b-5848-4704-af42-cac7f168b3b6 dataSourceKey=main
[31m2025-06-01 02:21:21 [error] Erro interno do servidor ao atualizar programação[39m meta={"err":"InternalServerError: Erro interno do servidor ao atualizar programação\n    at Object.throw (/root/www/my-nocobase-app/node_modules/koa/lib/context.js:97:11)\n    at updateWeekDay (/root/www/my-nocobase-app/packages/plugins/@sigmacore/kanban/src/server/plugin.ts:161:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)\n    at async setCurrentRole (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/middlewares/setCurrentRole.js:87:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async app.resourcer.use.group (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-api-keys/dist/server/plugin.js:62:9)\n    at async AuthManagerMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/auth-manager.js:125:7)\n    at async validateFilterParams (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/validate-filter-params.js:39:12)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/plugin-locale-tester/dist/server/plugin.js:56:7"} module=kanban_programacoes submodule=updateWeekDay method=error-handler app=main reqId=804f39f8-725e-4933-8752-560c173f906a dataSourceKey=main
[31m2025-06-01 02:23:50 [error] Cannot read properties of undefined (reading 'getConfig')[39m stack=TypeError: Cannot read properties of undefined (reading 'getConfig')
    at BasicAuth.checkToken (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/base/auth.js:146:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _AsyncEmitter.<anonymous> (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-auth/dist/server/plugin.js:176:17) module=application app=main reqId=57dfe12c-d3b5-4091-8f14-d7e05ab7c74b dataSourceKey=main
[31m2025-06-01 02:24:05 [error] Erro ao atualizar programação               [39m meta={"err":"InternalServerError: Erro ao atualizar programação\n    at Object.throw (/root/www/my-nocobase-app/node_modules/koa/lib/context.js:97:11)\n    at updateWeekDay (/root/www/my-nocobase-app/packages/plugins/@sigmacore/kanban/src/server/plugin.ts:184:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)\n    at async setCurrentRole (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/middlewares/setCurrentRole.js:87:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async app.resourcer.use.group (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-api-keys/dist/server/plugin.js:62:9)\n    at async AuthManagerMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/auth-manager.js:125:7)\n    at async validateFilterParams (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/validate-filter-params.js:39:12)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/plugin-locale-tester/dist/server/plugin.js:56:7"} module=kanban_programacoes submodule=updateWeekDay method=error-handler app=main reqId=365518d3-fdab-4b10-8a42-e039b76a5f1e dataSourceKey=main
[31m2025-06-01 02:25:12 [error] Erro ao atualizar programação               [39m meta={"err":"InternalServerError: Erro ao atualizar programação\n    at Object.throw (/root/www/my-nocobase-app/node_modules/koa/lib/context.js:97:11)\n    at updateWeekDay (/root/www/my-nocobase-app/packages/plugins/@sigmacore/kanban/src/server/plugin.ts:184:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async triggerWorkflowActionMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-workflow-action-trigger/dist/server/ActionTrigger.js:61:7)\n    at async dataTemplate (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/data-template.js:36:3)\n    at async app.acl.use.after (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/server.js:534:9)\n    at async middlewares.add.tag (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:398:9)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/allow-manager.js:108:7\n    at async ACLMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/acl/lib/acl.js:288:14)\n    at async setCurrentRole (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-acl/dist/server/middlewares/setCurrentRole.js:87:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async setDepartmentsInfo (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-departments/dist/server/middlewares/set-departments-roles.js:66:3)\n    at async app.resourcer.use.group (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-api-keys/dist/server/plugin.js:62:9)\n    at async AuthManagerMiddleware (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/auth-manager.js:125:7)\n    at async validateFilterParams (/root/www/my-nocobase-app/node_modules/@nocobase/server/lib/middlewares/validate-filter-params.js:39:12)\n    at async /root/www/my-nocobase-app/node_modules/@nocobase/plugin-locale-tester/dist/server/plugin.js:56:7"} module=kanban_programacoes submodule=updateWeekDay method=error-handler app=main reqId=1bbe17a1-491b-414b-a251-3bad861ae8e8 dataSourceKey=main
[31m2025-06-01 02:27:04 [error] Cannot read properties of undefined (reading 'getConfig')[39m stack=TypeError: Cannot read properties of undefined (reading 'getConfig')
    at BasicAuth.checkToken (/root/www/my-nocobase-app/node_modules/@nocobase/auth/lib/base/auth.js:146:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _AsyncEmitter.<anonymous> (/root/www/my-nocobase-app/node_modules/@nocobase/plugin-auth/dist/server/plugin.js:176:17) module=application app=main reqId=32dd732f-d95d-4137-9c2a-0efd7f2b10d5 dataSourceKey=main
